package main

import (
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"time"

	"github.com/flidai/autback/internal/console"
)

func main() {
	types := []reflect.Type{
		reflect.TypeOf(console.SessionView{}), reflect.TypeOf(console.ProjectView{}),
		reflect.TypeOf(console.ServiceView{}), reflect.TypeOf(console.WorkerView{}),
		reflect.TypeOf(console.QueueView{}), reflect.TypeOf(console.OperationView{}),
		reflect.TypeOf(console.OperationDetailView{}), reflect.TypeOf(console.CacheView{}),
		reflect.TypeOf(console.LogView{}), reflect.TypeOf(console.AuditView{}),
		reflect.TypeOf(console.StatusView{}),
	}
	var output strings.Builder
	output.WriteString("// Code generated by go generate ./internal/console. DO NOT EDIT.\n\n")
	for _, value := range types {
		writeInterface(&output, value)
	}
	output.WriteString(`export interface ConsoleSignals {
  session: SessionView
  service: ServiceView
  worker: WorkerView
  queue: QueueView[]
  operations: OperationView[]
  operation: OperationDetailView | null
  log: LogView
  audit: AuditView[]
  status: StatusView
}
`)
	path := filepath.Join("..", "..", "web", "generated", "console.ts")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(path, []byte(output.String()), 0o644); err != nil {
		panic(err)
	}
}

func writeInterface(output *strings.Builder, value reflect.Type) {
	extends := ""
	for index := 0; index < value.NumField(); index++ {
		field := value.Field(index)
		if field.Anonymous {
			extends = " extends " + dereference(field.Type).Name()
		}
	}
	fmt.Fprintf(output, "export interface %s%s {\n", value.Name(), extends)
	for index := 0; index < value.NumField(); index++ {
		field := value.Field(index)
		if field.Anonymous {
			continue
		}
		name := strings.Split(field.Tag.Get("json"), ",")[0]
		if name == "" {
			name = field.Name
		}
		if name == "-" {
			continue
		}
		fmt.Fprintf(output, "  %s: %s\n", name, typeScriptType(field.Type))
	}
	output.WriteString("}\n\n")
}

func typeScriptType(value reflect.Type) string {
	if value == reflect.TypeOf(time.Time{}) {
		return "string"
	}
	switch value.Kind() {
	case reflect.Pointer:
		// Datastar applies null as a signal deletion, so a Go pointer can be
		// absent from the materialized browser object as well as explicitly null.
		return typeScriptType(value.Elem()) + " | null | undefined"
	case reflect.Slice, reflect.Array:
		return typeScriptType(value.Elem()) + "[]"
	case reflect.Map:
		return "Record<" + typeScriptType(value.Key()) + ", " + typeScriptType(value.Elem()) + ">"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64, reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Float32, reflect.Float64:
		return "number"
	case reflect.String:
		return "string"
	case reflect.Struct:
		return value.Name()
	default:
		panic("unsupported console contract type " + value.String())
	}
}

func dereference(value reflect.Type) reflect.Type {
	for value.Kind() == reflect.Pointer {
		value = value.Elem()
	}
	return value
}
